FE/public/index.html
FE/src/App.js
FE/src/components/header.js
FE/src/index.js
FE/src/pages/Mainpage.js

FE 디렉토리 구조 설정 및 예제 파일 생성
- FE 디렉토리 구조를 설정함
- 예제 파일을 생성하여 repo에 빈 폴더도 같이 올라갈 수 있도록 함
```
├─ FE
│  ├─ .eslintrc.js
│  ├─ .prettierrc
│  ├─ package-lock.json
│  ├─ package.json
│  ├─ public
│  │  └─ index.html
│  └─ src
│     ├─ App.js
│     ├─ components
│     │  └─ header.js
│     ├─ index.js
│     └─ pages
│        └─ Mainpage.js
```
없음
close #10

Feat: FE 디렉토리 구조 설정 및 예제 파일 생성

---

FE/.eslintrc.js
FE/package-lock.json
FE/package.json
FE/public/index.html
FE/src/index.js
FE/src/pages/GamePage.js
FE/src/pages/GuestPage.js
FE/src/pages/LoginPage.js

index.html에서 view 부분 파일로 분리, history API 구현, SPA 화면 이동 구현, 게임페이지 분리 및 PONG 프로토타입 삽입
- index.html에서 view 부분 파일로 분리
- history API 구현
- 뒤로가기, 앞으로가기 작동(특정 행동 시 버그 존재 가능성 있음)
- SPA 화면 이동 구현
- 로그인 페이지에서만 새로고침 가능
- 게임페이지 분리 및 PONG 프로토타입 삽입
- WebSocket 부분은 아직 구현 X, 일요일에 백엔드와 상의하며 구현 예정
close #16

[Feat] index.html에서 view 부분 파일로 분리, history API 구현, SPA 화면 이동 구현, 게임페이지 분리 및 PONG 프로토타입 삽입

---

.gitignore
GAME/match/match_manager.py
GAME/websocket/consumers.py

게임 매치 패들 움직임 업데이트 로직 수정
- 클라이언트는 key_set이 변경될 때마다 웹소켓으로 데이터 전송
- 게임 서버는 매 프레임마다 key_set(keys)를 확인하여 패들 움직임 업데이트
(3/12 데일리스크럼 내용 반영)
**[ 게임 매치 패들 움직임 업데이트 로직 수정 ]**
- MatchManager 객체에 `keys` 리스트 멤버변수 추가
- 현재 pylint에서  `R0902: Too many instance attributes (8/7) (too-many-instance-attributes)` 발생중
- 추후 수정 필요
- 패들 움직임 업데이트
- `MatchManager` 객체의 `start_game()` 함수 내부 무한 루프(1초당 60프레임 전송) 내부에서 진행
- 멤버 함수 `local_move_paddles()` 에서 멤버 변수 `keys`에 저장된 키 값을 확인하여 패들 좌표 업데이트
- 공 움직임과 동일하게 업데이트됨
- 웹소켓으로 key_down 서브타입 메시지 수신된 경우 `keys` 리스트에 저장
- 클라이언트에서 `key_set`이 변경될 때마다 웹소켓으로 데이터 전송
```python
async def receive(self, text_data=None, bytes_data=None):
msg = json.loads(text_data)
msg_type, msg_subtype, msg_data = msg["type"], msg["subtype"], msg["data"]
if msg_type == "game" and msg_subtype == "key_down": …
```

[Feat] 게임 매치 패들 움직임 업데이트 로직 수정

---

BE/backend/settings.py
GAME/game_server/settings.py
GAME/match/attack_stat.py
GAME/match/ball.py
GAME/match/match_manager.py
GAME/match/paddle.py
GAME/match/player.py
GAME/websocket/consumers.py

게임 매치 통계 데이터 1차 수집 
- 경기 날짜 및 경기 시간
- 랠리 횟수 (최대, 평균, 최소)
- 최대 공속도 (최대, 평균 최소)
- 공격 성향
- 평균 키 입력 횟수
[ 게임 매치 통계 데이터 1차 수집 ]
- `end_game` 함수 호출 시 통계 데이터 전송
- 웹소켓 규약 맞춰서 전송
- 구현되지 않은 값은 임시값으로 저장하여 전송
- `AttackStat` 클래스 구현
- 현재 공격 성향을 확인할 수 있는 로직이 포함되어 있음
- 파워 업 및 주요 유효 공격 위치에 대한 통계 데이터 로직이 추가될 예정
- 그래프를 표시하는 데이터도 포함될 수 있음
- 경기 날짜 및 경기 시간
- `django.utils`의 `timezone` 모듈 활용
- 랠리 횟수 (최대, 평균, 최소)
- 랠리에 대한 정보는 현재 `MatchManager`가 관리 
- 최대 공속도 (최대, 평균 최소) 
- `Ball` 클래스가 관리
- 현재 공 속도가 변화하는 로직이 존재하지 않아 추후 확인 필요
- 공격 성향
- `AttackStat` 클래스 내부 구현
- 패들을 4등분하여 위(1/4)와 아래(1/4)는 공격형, 중앙(1/2)는 방어형, 같으면 혼합형으로 반환
- 평균 키 입력 횟수
- 랠리당 평균 키 다운 횟수 통계 저장
- `Player` 객체에서 랠리에 대한 키 다운 횟수를 관리 후 득점 시 `AttackStat`의 리스트에 저장
**[ 기타 ]**
- timezone 세팅 변경
- Asia/Seoul로 변경
- 이전에는 UTC 사용
- 상수 자료형 Final로 설정
- 좌표 경계 계산 함수를 분리 
- …

[Feat] 게임 매치 통계 데이터 1차 수집 

---

FE/src/pages/GamePage.js

게임 애니메이션 및 룰 추가
- 도입부 애니메이션
- 겁나 멋진 ready 문구 출력
- 반짝이며 시작하는 효과 추가
- 이사만루 폰트 적용
- 게임 룰 추가
- 왼쪽, 오른쪽 벽 닿을 시 점수 추가
- 게임 시작 및 득점 직후 공 속도 감속
- 점수판 추가
- 10선 승 시 게임 종료
머찐 작업은 직접 체험해보세요.. 머찝니다..
- close #29

[Feat] 게임 애니메이션 및 룰 추가

---

FE/src/pages/GamePage.js

게임 서버에서 받아온 정보로 게임을 render하도록 변경 
- 기존 js 페이지로 넘어온 배경 색, 패들 색으로 게임을 render하는 과정에서, 게임 서버에서 보내온 정보를 이용하여 배경 색, 패들 색을 render하도록 변경
- 웹소켓 규약에 따라 통신하고, 설정을 변경하도록 함
없음
close #48

[Fix] 게임 서버에서 받아온 정보로 게임 render하도록 변경

---

FE/src/pages/GameSettingDetailed.js
FE/src/pages/GameSettingPage.js

게임 세부 설정 UI에서 초기화가 되지 않는 오류 해결
- 게임 세부 설정 페이지에서 초기화 버튼과 완료 버튼을 눌렀을 경우 페이지 전환을 위해 changeUrl 함수가 호출되어 변수로 입력한 기존 data가 전달되지 않는 오류 확인
- changeUrlData 함수를 호출하여 변경된 data를 전달하도록 변경
- 게임 설정 페이지에서도 MatchModePage에서 넘어온 경우에만 초기 값을 세팅하고, 이외의 경우에는 인자로 넘어온 값을 이용하도록 변경
https://github.com/authenticity-house/ft_transcendence/assets/74870834/535b45dd-dd9a-4e49-b2d8-1f39c28adb5f
close #62

[Fix] 게임 세부 설정 초기화되지 않는 오류 해결

---

FE/public/css/styles.css
FE/public/index.html
FE/src/components/ActivateButtons.js
FE/src/components/InputNickname.js
FE/src/index.js
FE/src/pages/GameSettingDetailed.js
FE/src/pages/GameSettingPage.js
FE/src/pages/GameSettingTournament.js
FE/src/pages/MatchModePage.js

토너먼트 게임 설정 페이지 UI 제작 및 설정 초기화 오류 해결
1. 토너먼트 참여인원을 -, + 버튼을 눌러서 조절
- 기본 값 4
- 범위는 1~8로 하여 조절한 참여인원이 1이거나 8일 경우 -. + 버튼 비활성화
2. 토너먼트 참가자 닉네임 입력 UI
- InputNickname 컴포넌트
- start, end index를 인자로 넘겨 index와 input box 출력
- `const inputNickname1 = new InputNickname(1, 4);`
- 이후 입력을 받은 참가 인원에 따라 input창의 개수 조절과 입력을 받아 저장하는 부분 추가 필요
---
- gameSetting 페이지에 입력받은 setting값이 남아있어 초기화가 되지 않음
- game 실행 시 gameSetting 페이지의 this.data 초기화
- 깊은 복사를 위해 JOSN.parse(), JSON.stringify 함수 이용
```jsx
resetData() {
this.data = JSON.parse(JSON.stringify(this.initialData));
}
```
https://github.com/authenticity-house/ft_transcendence/assets/74870834/c5dcdd5d-47db-485f-9482-48bd3c06f871
[#47 ](https://github.com/authenticity-house/ft_transcendence/issues/47)
close #62

[Feat] 토너먼트 게임 설정 페이지 UI 제작 및 설정 초기화 오류 해결

---

GAME/Makefile
GAME/session/admin.py
GAME/session/apps.py
GAME/session/models.py
GAME/session/session_manager.py
GAME/session/tests.py
GAME/session/views.py
GAME/websocket/consumers.py

게임 세션 매니저 초기 구현
- `python manage.py startapp` 명령 사용
- Makefile에 검사 추가
- GameConsumer에서 MatchManager가 아닌 SessionManager를 사용하도록 변경
- 이전에는 1 vs 1만 고려하였기 때문에 가능
- 현재는 토너먼트에서 여러 매치가 진행되기 때문에 세션 매니저로 교체
- 모든 분기를 SessionManager가 관리하는 데이터를 요청하는 방식으로 구현
- 현재 완벽하게 분리하지는 않고 GameConsumer와 SessionManager가 섞여있음
- 그리고 매치 매니저가 생성되지 않았을 때와 같은 경우를 생각하지 않고 구현함
- 추후 웹소켓 규약과 함께 다시 정리 필요 
- SessionManager의 `get_match_frame` 함수는 yield from을 사용하여 값을 넘겨주도록 함
- 이전에 MatchManager의 값을 참조하여 가져다쓰는 것을 SessionManager가 중간에서 넘겨주도록 구현
- 현재 토너먼트가 클라이언트에서 구현되어 있지 않기 때문에 임시 클라이언트 코드로 수신 메시지 확인
- #57

[Feat] 게임 세션 매니저 초기 구현

---

FE/public/css/styles.css
FE/src/components/TournamentBracket.js
FE/src/pages/LoginPage.js
FE/src/pages/TournamentPage.js

- 토너먼트 페이지 리팩토링
- 코드 리팩토링
- TournamentPage : mount() 할때, 실행되던 function들을 component/TournamentBracket 으로 이동
- component/TournamentBracket : class형식에서 function으로 수정
- TournamentPage : Mock Data / 나중에 받아 올 데이터의 형식과 비슷하게 수정 
- 애니메이션 효과 적용
- 'PONG !' 문자열 데이터를 받으면, pong-animation 클래스 추가 되어 적용 (다음에 대결 해야 하는 대진 테이블)
- winPlayer 데이터를 받고, 문자열 데이터가 winPlayer와 같다면, win-player-animation 클래스 추가 되어 적용 (부전승 or 대결 후 이긴 플레이어 대진 테이블)
https://github.com/authenticity-house/ft_transcendence/assets/83465749/b5be4e7b-a90a-42cb-8cf3-8a137a06cee6
close #74

[Refactor] 토너먼트 페이지 리팩토링

---

FE/src/Gamewebsocket.js
FE/src/pages/GamePage.js

GamePage에서 Websocket 로직 분리
- GamePage에서 Websocket 로직 분리
- Class 형태로 Websocket을 분리하여, 토너먼트 형태에서도 new Gamewebsocket을 호출하여 사용할 수 있도록 설계
- this 키워드를 활용해 Gamepage 자체를 인자로 넘겨줌으로서 게임 내 요소들을 websocket 클래스 내에서 조작 가능하도록 설계
코드 리팩토링의 일환이기 때문에 스크린샷은 의미가 없어 생략합니다.
close #54

[Refactor] GamePage에서 Websocket 로직 분리

---

.gitignore
BE/Makefile
BE/backend/settings.py
BE/requirements.txt
GAME/game_server/settings.py
GAME/requirements.txt
docker-compose.yml

백엔드 서버 Django PostgreSQL 연동
> 참고: https://velog.io/@yvvyoon/python-env-dotenv
- 현재 도커 환경과 로컬 환경이 존재
- 도커에서는 .env 파일에 적힌 값이 시스템 환경변수로 들어감
- 로컬에서는 .env 파일에 적힌 값을 직접 가져와서 사용해야 함
- 따라서 `dotenv` 모듈을 통해 파일을 가져오고 이를 시스템 환경변수가 덮어쓰도록 되어있음
- .env 파일이 경로에 존재하지 않는다면 사용하지 않음
- `docker-compose.yml`에 `postgresql` 컨테이너 설정 추가
-  .env 파일이 수정되었기 때문에 변경 필요
- `data/postgres` 경로를 마운트하기 때문에 폴더가 있어야 함 -> 공유 필요..!
- `settings.py` 파일에 `postgresql` 설정 추가
> 하나의 마이그레이션 파일은 해당 마이그레이션이 생성된 시점의 모델의 구조(DB의 스키마)를 담고 있습니다.
> 참고: https://tibetsandfox.tistory.com/24
- db 설정이 변경되거나 모델이 변경되었을 경우 migrate를 해주어야 함
- 폴더 구조
- close #93

[Setting] 백엔드 서버 Django PostgreSQL 연동

---

FE/src/pages/GameSettingDetailed.js
FE/src/pages/online/OnlineGameSettingDetailed.js
FE/src/pages/online/OnlineGameSettingTournament.js

게임 설정 초기화 안되는 오류 해결
- 초기화 버튼을 누르면 초기 정보를 가지고 동일한 페이지를 로딩하는 방식
```
resetButton.addEventListener('click', () => {
...
changeUrlData('gameSettingDetailed', this.data);
});
```
- index.js에서 변경된 사항 : 페이지 관리를 위해 동일한 페이지일 경우 페이지를 변경하지 않음
때문에 기존 방식으로 초기화를 진행할 경우 데이터는 변경되지만 UI가 초기화 되지 않는 오류 발생
- changeColor 를 통해 요소 색깔과, 네온 효과를 한번에 적용할 수 있도록 변경
```
const changeColor = (
elementId,
element,
elementColorSelector,
boxShadowSelector
) => { ... }
```
- 승점과 난이도 선택 버튼을 탐색하며 인덱스를 기준으로 직접 초기화
```
document
.querySelectorAll('.activate-button')
.forEach((container, index) => {
container.querySelectorAll('button').forEach((btn, btnIndex) => {
btn.classList.remove('selected');
if ((index === 0 || index === 1) && btnIndex === 1) {
btn.classList.add('selected');
}
});
});
```
- 온라인 방 설정 부분에서 세부 설정으로 들어갈 경우 선택한 …

[Fix] 게임 설정 초기화 안되는 오류 해결

---

FE/public/css/font.css
FE/public/css/styles.css
FE/src/components/ModalGraphStats.js
FE/src/components/modal/profile_modal/GetContent.js
FE/src/components/modal/profile_modal/ProfileModal.js
FE/src/components/modal/profile_modal/StatsContent.js

- 모달 통계 UI 제작
- 총 플레이 타임 / 로컬, 온라인 시간
- 프로필 요약 / 승무패, 승률, 레이팅 점수
- 최고 기록 /  최고 레이팅 점수, 최고 공 속도, 최고 랠리 횟수 
- 레이팅 변화율 그래프 / 최근 10-30경기 레이팅 점수 
- 공격 성향 / 방어형, 공격형, 혼합형
```js
// template() 에서 띄우는 데이터
const mockData = {
nickName: '종식',
playTime: { local: '36m 24s', online: '1h 36m 50s' },
matchCount: { all: 1000, win: 500, lose: 500, winRate: 50 },
rating: 1500,
top: {
topRating: 1800,
topBallSpeed: 100,
topRallyCount: 55
},
ratingChange: [
1000, 1050, 1100, 1050, 1100, 1150, 1200, 1250, 1300, 1250, 1200, 1250
]
};
```
```js
// mount() 에서 띄우는 데이터 
const data = {
ratingChange: [
1000, 1050, 1100, 1050, 1100, 1150, 1100, 1150, 1200, 1150, 1200, 1250
],
attackTendency: [
{ title: '공격형', value: 50, color: '#ff5d84' },
{ title: '혼합형', value: 30, color: '#ffd164' },
{ title: '방어형', value: 20, color: …
```

[Feat] 모달 통계 UI 제작

---

BE/users/urls.py
BE/users/views.py

로그인 상태를 확인할 수 있는 API 구현
`GET /users/check-login/`
- 로그인 상태가 아닌 경우 403 반환
- 로그인 상태인 경우 200 반환
- 기존에 사용하던 view의 유저 권한 확인 기능을 사용함
```python
authentication_classes = [SessionAuthentication]
permission_classes = [IsAuthenticated]
```
- 로그인 상태가 아니면 권한이 없어 403이 반환됨
- 권한이 있는 경우 무조건 로그인 상태라고 판단하여 200 반환
```python
def get(self, request):
return Response(
{
"user_id": request.user.id,
"username": request.user.username,
"is_authenticated": True,
}
)
```
- 비로그인 상태에서 호출 시 -> 403
- 로그인 상태에서 호출 시 -> 200
- close: #157

[Feat] 로그인 상태 확인 API 구현

---

BE/backend/settings.py
BE/requirements.txt
BE/users/oauth.py
BE/users/urls.py
BE/users/views.py
FE/src/constants/constants.js
FE/src/pages/LoginPage.js
FE/src/pages/register/registerValidCheck.js
FE/src/websocket/MessageManager.js

OAuth를 이용한 회원가입 및 로그인
1. 메인 화면에서 **42 로그인** 버튼 클릭
2. 유저를 API 공급자의 OAuth 권한 부여 서버로 리다이렉션
```python
GET https://api.intra.42.fr/oauth/authorize
```
- `https://api.intra.42.fr/oauth/authorize?client_id=${client_id}&redirect_uri=${redirect_uri}&response_type=code`
- 쿼리 파라미터로 client_id, redirect_uri, response_type 포함
**OAuth 권한 서버**
1. 권한 서버는 사용자에게 active 세션이 있는지 확인(로그인 되어 있는지)
2. 권한 서버는 요청한 데이터에 액세스하라는 메시지를 표시
3. 유저가 액세스 권한을 부여한 후 웹 애플리케이션으로 다시 리다이렉션되고 인증 코드가 코드 쿼리 매개변수로 URL에 포함
`http://www.example.com/oauth_callback?code=ABC1234`
3. 부여받은 code를 포함하여 권한 서버로 POST 요청
```python
POST https://api.intra.42.fr/oauth/token
```
- Body = { “grant_type”, “code”, “client_id”, “client_secret”, “redirect_uri”, “scope” }
- 요청에 대한 응답
```python
{
"access_token": "example",
"token_type": "bearer",
"expires_in": …
```

[Feat] OAuth를 이용한 회원가입 및 로그인

---

FE/src/components/modal/profile_modal/FriendInfoContent.js
FE/src/components/modal/profile_modal/GetContent.js
FE/src/components/modal/profile_modal/MyInfoContent.js
FE/src/constants/apiConfig.js

내 정보 / 친구 정보 요약 통계 api 연결
내 정보 / 친구 정보 요약 통계 api 연결
- 403일 경우 alert으로 경고 후 새로 고침.
- 404일 경우 모든 값이 0인 데이터로 대체
close #178

[Feat] 내 정보 / 친구 정보 요약 통계 api 연결

---

FE/public/css/font.css
FE/public/css/styles.css
FE/src/components/DuelBasicStats.js
FE/src/components/MyFriendRequestNode.js
FE/src/components/TournamentBracket.js
FE/src/components/modal/profile_modal/StatsContent.js
FE/src/pages/online/rooms/waitingRoom/WaitingRoomUserBox.js

문자열 길이에 따른 폰트 크기 조절 2차
문자열 길이에 따른 폰트 크기 조절 2차
- 온라인 대기 화면
- 대진표
- 친구 요청 노드
close #228

[Fix] 문자열 길이에 따른 폰트 크기 조절 2차

---

FE/public/css/font.css
FE/public/css/styles.css
FE/src/components/modal/profile_modal/GetContent.js
FE/src/components/modal/profile_modal/MyInfoContent.js
FE/src/game/GamePage.js
FE/src/pages/online/rooms/roomManager.js
FE/src/pages/online/rooms/waitingRoom/WaitingRoomPage.js

관전자 시각화
관전자 시각화
- 온라인에서만 작동
- 관전자일 경우 게임 화면 중앙에 희미하게 워터마크마냥 관 전 모 드 적혀서 출력
close #236

[Feat] 관전자 시각화

---

FE/src/index.js

- 방 대기실에서 모달 창 열린 상태에서 게임 시작 시 모달 창 열린 상태인 문제
- url 바뀔때 마다 모달 닫아주는 코드 삽입해서 모달 창을 일괄적으로 닫아줬습니다!
🙅🏻‍♂️
#245

[Hotfix] 방 대기실에서 모달 창 열린 상태에서 게임 시작 시 모달 창 열린 상태인 문제
