BE/Makefile
BE/backend/settings.py
BE/requirements.txt
GAME/Makefile
GAME/game_server/settings.py
GAME/requirements.txt

- python 내 타입 검사를 위해 mypy를 추가로 도입 및 Makefile 수정
- mypy 추가
- Makefile에 타입 검사, 유닛 테스트 명령어 추가
- `make type`: mypy를 이용한 타입 검사 수행
- `make test`: django 내장 테스트 프레임워크를 이용한 테스트 수행
- GAME 프로젝트의 settings.py에 DEBUG 환경 변수가 누락되어 있던 부분 수정
- close: #6

[Feat] BE 타입 검사 추가

---

GAME/websocket/consumers.py

게임 서버와 클라이언트에 로컬 1대1 웹소켓 규약을 적용
- 게임이 시작되면 task 등록 후 game_session에 저장
- 연결이 종료되어 disconnect 함수 호출 시 game_session을 종료
- 서로 통신 규약을 올바르게 지켰을 때만 고려
- 클라이언트가 보낸 총점 정보를 MatchManager에 적용
```python
self.match_manager = MatchManager(socket=self, total_score=msg_data["total_score"])
```
- 이외의 게임 초기화 부분은 미구현되어 주석 처리
- 수신 받은 메시지별로 행동해야할 구역 구분
```javascript
async function receiveMessages() {
websocket.onmessage = (event) => {
const message = JSON.parse(event.data);
switch(message.type) {
// 1-2. 커넥션 연결 성공 메시지 전송
case "connection_established":
// 2-1. 게임 서버로 게임 초기 정보 전송
sendGameSessionInfo();
break;
case "game":
// 2-2. 클라이언트로 게임 초기 정보 전송
if(message.subtype === "match_init_setting") {
// 게임 시작 준비 완료 후 시작 요청 메시지 전송
sendGameStartRequest();
// 3-2. 클라이언트로 게임 매치 데이터 전송
} else if (message.subtype === …
```

[Feat] 게임 서버-클라이언트 로컬 1대1 웹소켓 규약 적용

---

GAME/Makefile
GAME/match/ball.py
GAME/match/match_manager.py

공이 벽을 뚫고 무한 반사하는 문제 해결
> 자세한 해결 과정 참고 : [개발 일지](https://lowly-crepe-78b.notion.site/bc7da9de526e4a61ac0df3d40619ef54?pvs=4)
**[ 문제점 ]**
- 공과 벽의 충돌을 판단할 때 공의 이동방향을 고려하지 않음
- 공의 좌표를 변화시킬 때 스크린을 벗어났는지 확인하지 않음
**[ 해결 ]**
1. 공과 벽의 충돌 여부를 판단할 때 공의 이동방향을 고려
- 공의 dy 부호 값을 확인하여 벽에 부딪히는 이동방향인지 확인
```python
def is_ball_colliding_with_wall(self) -> bool:
"""벽 충돌 확인"""
ball_y_bound = self.ball.ball_y_bound
return (self.ball.y <= -ball_y_bound and self.ball.dy < 0) or (
ball_y_bound <= self.ball.y and 0 < self.ball.dy
)
```
2. 공의 좌표가 스크린을 벗어난 경우 스크린 내부 좌표로 값을 할당
- 벽에 부딪혔다고 판단하는 경우는 y좌표만을 확인하기 때문에 이에 대한 조건문 추가
- x 좌표가 스크린을 벗어난 경우 득점으로 판단하기 때문에 변경이 필요하지 않음
- `@property`를 활용하여 `ball_y_bound` `getter` 구현
- 공의 y좌표가 위치할 수 있는 최대값을 의미
- 실제 멤버변수 getter가 아닌 계산 값 반환
```python
def move_pos(self) -> None:
self._x …
```

[Fix] 공이 벽을 뚫고 무한 반사하는 문제 해결

---

FE/.eslintrc.js
FE/public/css/styles.css
FE/src/components/TournamentBracket.js
FE/src/index.js
FE/src/pages/MatchModePage.js
FE/src/pages/TournamentPage.js

토너먼트 대진표 UI 구현
- 토너먼트 대진표 유저의 수 만큼 대진표가 자동적으로 그려지게끔 설계
- FE/src/components/TournamentBracket.js 안에 Mock Data 주석 달아 놓은 곳의 player를 수정해서 잘 나오는지 확인해보세요~! 
- eslint Rule : for..of 문, contiue 코드 off 
https://github.com/authenticity-house/ft_transcendence/assets/83465749/6638e80e-ab8d-4880-a9ea-dfd569132cb1
close #52

[Feat] 토너먼트 대진표 UI

---

GAME/match/coor_util.py
GAME/match/paddle.py
GAME/websocket/consumers.py

CCW 알고리즘으로 패들 충돌 판별하도록 로직 수정
**[ CCW 알고리즘으로 패들 충돌 판별 ]**
> 자세한 해결 과정 참고 : [학습 + 개발 일지](https://www.notion.so/CCW-6a22a19026574fcaadd319f705365c7c?pvs=4)
- 공 속도가 공의 가로 길이보다 커지면 패들을 관통하는 버그 해결을 위함
- 패들의 테두리와 공의 이동 선분의 교차여부를 확인
- 추가로 좌표 계산 함수 모듈화(`coor_util.py`)
- 함수의 매개변수가 많아져 Point라는 클래스를 좌표 계산 시 사용 
<br><br>
**[ 게임 초기 설정 실제 정보 반영 ]**
- 클라이언트에게 전송하는 정보를 MatchManager가 가진 정보를 반영하도록 수정
- 확인해보니 클라이언트에서도 상수값을 사용하기 때문에 반영 필요함
- #45

[Feat] CCW 알고리즘으로 패들 충돌 판별

---

FE/src/pages/GamePage.js
GAME/match/match_manager.py
GAME/websocket/consumers.py

로컬에서 게임 연결 후 나가기 버튼을 눌렀을 때 게임 세션이 종료되는 기능을 추가했습니다.
- 프론트 코드에 return을 누르면 웹소켓으로 disconnect 메시지를 보내도록 추가
- 원인: 클라이언트로 인해 웹소켓이 닫힌 이후에 비동기 task에 의해 send 되는 예외 발생
- 해결
- GameConsumer에 웹소켓의 현재 상태를 저장하는 변수(connected) 추가
- connect 메시지가 도착했을 때 True, disconnect 메시지가 도착했을 때 False가 됨
- connected가 False인 상태에서 웹소켓 통신을 시도한 경우에 무시
- 기존에는 MatchManager가 직접 웹소켓으로 send를 하고 있었음
- GameConsumer의 메서드를 사용하여 전송하도록 수정
- 이를 통해 웹소켓이 닫힌 경우 send 되는 현상을 방지
- MatchManager에서 GameConsumer를 추가하게 되자 서로 참조하는 순환참조 현상이 발생
- 당장 이를 고치기는 어려워 우선 동적 바인딩에 의존하도록 임시 수정
- 리팩토링 과정에서 새로운 객체를 도입해 순환 참조 현상 해결 예정
https://github.com/authenticity-house/ft_transcendence/assets/43935708/50ab0501-4d71-47b1-b605-0ccba4ec8ca4
- #55

[Feat] 로컬 게임 나가기 구현

---

FE/src/pages/GamePage.js
GAME/match/match_manager.py

게임이 종료된 후 3초간 패들 무빙 추가
- 기존에는 게임이 종료되면 바로 통계창으로 넘어갔음
- 변경 로직
1. 클라이언트는 게임이 종료됐다고 판단하면 승자에게 카메라 포커스
2. 게임 서버는 게임이 종료된 후 180 프레임동안 공 정지
3. 게임 서버가 180프레임을 기다린 후 통계 메시지를 보내면 클라이언트는 통계창으로 전환
https://github.com/authenticity-house/ft_transcendence/assets/43935708/31e37493-d634-4846-a589-17ca06b89e34
- #54

[Feat] 게임 종료 후 패들 움직이기 추가

---

FE/public/css/font.css
FE/public/css/styles.css
FE/src/pages/GamePage.js

게임 페이지 플레이어 닉네임 출력, 득점 시 애니메이션 효과 추가
- 게임 페이지 플레이어 닉네임 출력
- match_init_setting에서 받아온 데이터의 nickname을 활용하여 렌더링
- 득점 시 애니메이션 효과 추가
```css
@keyframes score_transition {
from {
text-shadow:
0rem 0rem 1rem #ff5d84,
0rem 0rem 1rem #ff5d84;
}
to {
text-shadow: none;
}
}
.score_transition {
animation: score_transition 3s;
}
```
- 같은 애니메이션을 반복 적용하기 위해 기믹 적용
- https://velog.io/@jminkyoung/TIL-35-JavaScript%EB%A1%9C-CSS-%EC%95%A0%EB%8B%88%EB%A9%94%EC%9D%B4%EC%85%98-%EC%9E%AC%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0
https://github.com/authenticity-house/ft_transcendence/assets/49023654/1112f8f9-152b-4760-89a8-6d3cbfe47385
close #40

[Feat] 게임 페이지 플레이어 닉네임 출력, 득점 시 애니메이션 효과 추가

---

FE/public/css/font.css
FE/public/css/styles.css
FE/src/components/GraphScore.js
FE/src/index.js
FE/src/pages/DuelStatsPage.js

게임결과 득점 추이 그래프 구현
- DuelStatsPage에 득점 추이 그래프 추가
- canvas 태그를 이용한 득점 추이 그래프 구현
- canvas 태그 사용법 링크  [HTML Canvas](https://www.w3schools.com/graphics/canvas_intro.asp) 
---
1. 그래프를 만드는데 필요한 데이터 가져오기
```js
const leftScoreTrend = data ? data.graph.player1.score_trend : [];
const rightScoreTrend = data ? data.graph.player2.score_trend : [];
const leftScore = data ? data.player1.score : 15; 
const rightScore = data ? data.player2.score : 15;
const maxScore = leftScore >= rightScore ? leftScore : rightScore;
```
2. maxScore에 따라서 좌측에 득점 텍스트 그리기 
```js
function graphScoreText(maxScore);
```
3.  좌측 득점 텍스트의 상대 좌표(y좌표) 얻기
```js
const position = getScoreTextPosition();
```
4. canvas 안에 점과 선을 알맞은 위치에 그리기
```js
function graphScoreTrend(leftScoreTrend, rightScoreTrend, position);
```
4-1. 점 그리기 함수
```js …
```

[Feat] 게임결과 득점 추이 그래프 구현

---

FE/src/components/InputNickname.js
FE/src/pages/GameSettingDetailed.js
FE/src/pages/GameSettingTournament.js

게임 설정 페이지 이동시 정보 저장 및 전달
1. 페이지 이동 시 정보 저장
토너먼트 초기 데이터 
```
this.initialData = {
battle_mode: 2,
total_score: 2,
level: 2,
color: {
paddle: '#5AD7FF',
ball: '#FFD164'
},
headcount: 4,
nickname: ['', '', '', '']
};
```
- 1vs1 / 토너먼트 버튼 눌러서 변경시 데이터 초기화
- 토너먼트 설정창에서 세부 설정 창 혹은 게임 페이지로 이동시 페이지에서 설정된 참여인원 수와 닉네임 저장
2. InputNickname
- containDiv(index, nickname)
-  index만 받아서 index 만큼 입력창을 만드는 부분에서 index와 nickname을 받아서 index만큼 입력창을 만들고, 그에 맞는 nickname을 입력창에 세팅하도록 변경
3. 참여 인원 3 ~ 8으로 제한
- 참여인원이 3명 이하일 경우 '-' 버튼 비활성화
- 참여인원이 3명 이하일 경우 '-' 버튼 비활성화
#47

[Feat] 게임 설정 페이지 이동시 정보 저장 및 전달

---

GAME/match/match_manager.py
GAME/match/paddle.py
GAME/session/bracket.py
GAME/session/session_manager.py

대진표를 반영하여 토너먼트의 각 매치를 순서대로 진행
- SessionManager의 `get_level_info()`에서 난이도에 따른 **패들 길이, 공 속도, 공 가속도** 반환
- level 1: 0.5, 0.04, 0.003
- level 2: 0.4, 0.04, 0.004
- level 3: 0.3, 0.05, 0.004
- Bracket 클래스 구현
- 현재 대진중인 매치에 대한 정보를 대진표에 추가 : `MATCH_PLAYING: Final = "PONG !"`
- 아직 경기가 진행되지 않은 상태 : `MATCH_NOT_START: Final = ""`
- 대진표를 보낼 때 진행되지 않은 것 또한 모두 형식에 맞춰 보내고 있음(3차원 배열 형태로 전송)
- 매치에서 이긴 사람은 winner로 전송(없다면 `""`)
```json
[
[
["wonyang", "jeongmin"], 
["joyoo", "jihylim"]
], 
[
["wonyang", "PONG !"]
],
[
[""]
]
]
``` 
- `latest` 정보 제거
- 토너먼트 대진표 전송 시 `winner` 추가, `depth -> bracket`으로 이름 변경
- `bracket` 형식 수정
- #57

[Feat] 대진표를 반영하여 토너먼트 진행

---

FE/public/css/styles.css
FE/public/image/duel-detail-button.svg
FE/src/components/DuelReport.js
FE/src/index.js
FE/src/pages/LoginPage.js
FE/src/pages/TournamentResultPage.js

- 토너먼트 경기 결과 요약 페이지 UI 제작
- TournamentResultPage 제작
- DuelReport component 제작 (매치 결과 한개)
---
- 디테일 정보 버튼 클릭 시, 통계들을 보여주는 UI 아직 구현하지 못했습니다.
- DuelStatsPage (단일 경기 결과 페이지) 에서 사용한 통계들이 컴포넌트로 나누어서 작성하지 않았기에 그대로 가져오는 것이 불가한 상태입니다. 
- 따라서 일단 완성한 UI 먼저 PR 요청 했고, DuelStatsPage 통계 관련 UI 컴포넌트로 나눈 후에, 디테일 정보 통계 UI 를 제작 할 예정입니다.
- 로그인 페이지 -> 로그인 버튼 클릭 -> 토너먼트 경기 결과 요약 페이지 UI
#77

[Feat] 토너먼트 경기 결과 요약 페이지 UI 제작 (50%)

---

FE/public/css/styles.css
FE/src/components/DuelBasicStats.js
FE/src/components/DuelGraphStats.js
FE/src/components/DuelSpecialStats.js
FE/src/components/DuelStatsData.js
FE/src/components/GraphScore.js
FE/src/pages/DuelStatsPage.js
FE/src/pages/LoginPage.js

- 게임 결과 통계 페이지(DuelStatsPage) 리팩토링
1. Data 선언 코드 줄이기
- 기존 DuelStatsPage template()에 있었던 데이터 관련 선언들을 DuelStatsData.js -> getDuelStatsData(data) 함수로 받아 오도록 수정
- DuelStatsPage mount()에 있었던 데이터 관련 선언들 또한 DuelStatsData.js -> getMountDuelStatsData(data) 함수로 받아 오도록 수정
2. DuelStatsPage template() 안의 Html 코드 컴포넌트로 분리
- 컴포넌트 파일 DuelBasicStats.js / DuelSpecialStats.js / DuelGraphStats.js 안에 정적 메소드로 정의
3. DuelStatsPage mount() 안의 사용했던 컴포넌트 함수들 리팩토링
- DuelGraphStats.js 안에 appendScoresToYAxis, appendScoreTrendGraph, appendScorePositionGraph 정적 메소드로 정의
- 기존 200줄 이상의 template() 함수 코드를 컴포넌트로 분리 하여 스크린샷과 같이 수정
close #83

[Refactor] 게임 결과 통계 페이지(DuelStatsPage) 리팩토링

---

FE/src/pages/GameSettingPage.js
GAME/match/ball.py
GAME/session/session_manager.py
GAME/websocket/consumers.py

로컬 1vs1 게임이 작동되지 않는 문제 해결
- 로컬 1vs1 시작할 때 전송되는 nickname 데이터 값 수정
- SessionManager를 1vs1과 토너먼트에 따라 분리
- 이전에는 `nickname: []`을 전송하면 게임 서버에서 nickname 정보를 저장할 때 빈 값이 저장되면서 파싱 오류 발생
- `nickname: ['player1', 'player2']` 로 기본 값을 포함하도록 변경
- 이전에 `SessionManager`에 구현되어있던 부분을 모두 분리
- 추상 클래스 `ASessionManager` 구현
- 추상 클래스 사용을 위해 `abc` 모듈 import
- 상속받는 자식 클래스에서 구현해야 하는 함수에는 `@abstractmethod`  데코레이터 사용 
- 1vs1을 위한 `DuelManager` 구현
- 토너먼트를 위한 `TournamentManager` 구현
- 현재 매치 초기 정보 전송 시 공 반지름에 대한 정보가 존재하지 않음
- 이를 포함해서 전송하도록 수정
- close #86

[Hotfix] 로컬 1vs1 게임이 작동되지 않는 문제 해결

---

FE/src/components/TournamentBracket.js
FE/src/pages/TournamentPage.js

- 토너먼트 대진표 페이지 - 데이터 받아서 대진표 띄우기 
- 웹소켓으로 토너먼트 대진표 데이터를 받습니다.
- 대진표 데이터를 파싱하여 알맞은 대진표 위치에 넣습니다.
스크린샷을 첨부해주세요.
- close #89

[Feat] 토너먼트 대진표 페이지 - 데이터 받아서 대진표 띄우기

---

FE/src/Gamewebsocket.js

토너먼트 모드 2번째 판부터 Ready가 보이지 않는 오류 수정
토너먼트 모드 2번째 판부터 Ready가 보이지 않는 오류 수정
음슴!
음슴!

[Hotfix] 토너먼트 모드 2번째 판부터 Ready가 보이지 않는 오류 수정

---

GAME/session/bracket.py
GAME/session/session_manager.py

- 토너먼트에서 게임 종료 판단 로직 수정
- 레벨에 따른 공 속도 수정
- 이전에는 빈 문자열인 경우, 게임을 진행하지 않았다고 판단했으나 닉네임이 빈 값이 들어오는 경우 처리가 제대로 되지 않아 인덱스 에러 발생
- 빈 문자열이 닉네임으로 들어왔을 때도 확인하기 위해 로직 수정
- 매치 랠리마다 기본 속도로 시작한 후 패들에 공이 닿았을 때 레벨에 맞는 속도로 변경
- 이때 기본 속도와 레벨 속도가 동일해서 변경되지 않는 오류 수정
- close #90

[Hotfix] 게임 종료 판단 오류 및 공 속도 수정

---

FE/public/css/styles.css
FE/src/components/DuelGraphStats.js
FE/src/components/DuelReport.js
FE/src/pages/LoginPage.js
FE/src/pages/TournamentResultPage.js

- 토너먼트 경기 결과 요약 페이지 데이터 띄우기
- 웹소켓으로 받아 온 데이터를 활용하여 경기 결과 요약 페이지를 만들기
- 이전에 DuelStatsPage에서 분리 했던 데이터 컴포넌트를 재사용 하기
- `.toggle()` 이용하여 상세 페이지 보이기 + 버튼 클릭 시, 버튼 이미지 바꾸기
```js
addEventListeners() {
const toggleButtons = document.querySelectorAll('.duel-toggle-button');
toggleButtons.forEach((button) => {
button.addEventListener('click', () => {
const parentWrapper = button.closest('.duel-report-wrapper');
const toggleContent = parentWrapper.querySelector(
'.duel-toggle-container'
);
toggleContent.classList.toggle('duel-toggle-hidden'); /* 상세 페이지 보이기 or 감추기 */
button.querySelector('img').classList.toggle('duel-button-roate'); /* 버튼 이미지 바꾸기 */
});
});
```
https://github.com/authenticity-house/ft_transcendence/assets/83465749/4fdc80c2-85e5-4e2d-96b6-87dcbd35ca5b
close #77

[Feat] 토너먼트 경기 결과 요약 페이지 데이터 띄우기

---

FE/public/css/font.css
FE/public/css/styles.css
FE/src/components/TournamentBracket.js
FE/src/pages/TournamentPage.js

- 토너먼트 대진표 페이지 - 우승자 UI 띄우기
- 토너먼트 대진표 페이지에서 마지막 우승자가 확정되었을 때의 UI 를 다르게 설정합니다.
- 타이틀 : '대진표' -> CHAMPION '우승자'
- 대진표 애니메이션 : 우승자 닉네임있는 곳 강조
- TournamentPage의 mount() 함수에서 마지막 우승자가 나타나면, 효과를 띄우게끔 코드 설정
```js
// tournament ending
const textElementAll = document.getElementsByTagName('p');
const lastBracketText = textElementAll[textElementAll.length - 1].innerText;
if (!(lastBracketText === '' || lastBracketText === 'PONG !')) {
// title change
replaceTitle('.bold-title', winPlayer);
// pong animation winPlayer
for (let i = 0; i < textElementAll.length; i += 1) {
if (textElementAll[i].innerText === winPlayer) {
textElementAll[i].parentNode.classList.add('pong-animation');
}
}
}
```
https://github.com/authenticity-house/ft_transcendence/assets/83465749/215ab706-2b0c-404e-9b68-d1842bacf4ac …

[Feat] 토너먼트 대진표 페이지 - 우승자 UI 띄우기

---

FE/public/css/styles.css
FE/src/index.js
FE/src/pages/MatchModePage.js
FE/src/pages/PlayModePage.js
FE/src/pages/RegisterNicknamePage.js
FE/src/pages/RegisterPage.js
FE/src/pages/TournamentPage.js

스크롤바 추가, 새로 고침 시 홈페이지로 링크 변경, history 로직 약간 수정 등
- 스크롤바 추가
- 새로 고침 시 홈페이지로 링크 변경
- 링크도 변경되고 화면도 변경됨
- 기존 페이지의 히스토리는 다 삭제됨
- history 로직 약간 수정
- game, duelstats, tournament, tournamentResult으로 history 변경하려고 할 경우
- 유효하지 않으므로 alert 띄우고 변경하지 않음.
- 링크도 변경하지 않음. (대신 alert이 떠있는 상태에서 다시 뒤로가기 하면 변경됨.)
-> 게임 화면으로 history 이동하려고 할 경우 
-> duelstats로 history 이동하려고 할 경우
#103

[Feat]  스크롤바 추가, 새로 고침 시 홈페이지로 링크 변경, history 로직 약간 수정 등

---

FE/src/Gamewebsocket.js
FE/src/index.js
FE/src/pages/DuelStatsPage.js
FE/src/pages/GamePage.js
FE/src/pages/GameSettingPage.js
FE/src/pages/GameSettingTournament.js
FE/src/pages/TournamentPage.js
FE/src/pages/TournamentResultPage.js
FE/src/websocket/Gamewebsocket.js
FE/src/websocket/MessageManager.js
FE/src/websocket/constWebsocket.js
FE/src/websocket/messages.js
FE/src/websocket/websocketUtils.js

프론트 websocket 관련 부분 리팩토링
1. GameSettingPage에서 ‘완료’ 버튼을 클릭하면 `new Gamewebsocket()`을 통해 새로운 웹소켓을 생성
2. Gamewebsocket 의 constructor
- `new Websocket()` 을 통해 게임 서버와 연결하고 멤버 변수를 초기화
- websocket이 open 되었으면 ‘connected’ 출력 후 `receiveMessages()`를 통해 서버에서 온 메시지 수신 후 처리
3. receiveMessages()
- switch/case를 통해 message.type에 따라 처리
- changeUrlData를 통해 페이지를 이동한 후 서버에게 [웹소켓 통신 규약](https://www.notion.so/c5f34b0c42814439895971d70eacadd2)에 따른 응답을 보내기 위해 페이지로 웹소켓을 인자로 받아서 이용
1. changeUrlData를 통해 페이지를 이동한 후 서버에게 통신 규약에 따른 응답을 보내기 위해 페이지로 웹소켓을 인자로 받아감
- Gamewebsocket.js
```jsx
receiveMessages() {
...
else if (message.subtype === 'match_init_setting') {
message.data.Gamewebsocket = this;
changeUrlData('game', message.data);
} 
...
}
```
- gamePage.js
```jsx
template() {
...
this.initial.Gamewebsocket.gamepage = …
```

[Refactor] 프론트 websocket 관련 부분 리팩토링

---

docker-compose.yml
nginx/nginx.conf

Nginx와 백엔드 서버 연결
> [관련 개발 일지 링크](https://lowly-crepe-78b.notion.site/Nginx-67e2723fbd434bf9840d340465505c70?pvs=4)
- 백엔드 서버 라우팅을 위한 location 추가
- `/api/` 로 시작하는 경로인 경우 nginx가 백엔드 서버로 전달
- 백엔드에서 DB를 찾지 못해 환경변수 설정 추가
- `docker-compose.yml`에 `environment` 활용
- `env_file`보다 우선순위가 높음
- postman에서는 csrftoken 값 설정이 필요하고 잘 설정했을 때 응답
- 브라우저에서 하면 css를 못찾는 이슈가 생김 (어짜피 개발용이라 상관 없을 듯)
- close #124

[Setting] Nginx와 백엔드 서버 연결

---

BE/users/adapters.py
nginx/nginx.conf

nginx.conf 파일에 CORS 에러 해결을 위한 헤더 추가
nginx에서 백엔드로 요청 전송 시 쿼리 파라미터가 누락되는 문제 해결
이메일 인증을 위해 보낸 링크에서 로그인 시도할 때 CORS 에러가 발생하는 문제가 있었음
이때는 백엔드 링크로 접근해서 프론트로 리다이렉션 된 후 로그인을 시도하기 때문에 발생된다고 추정
- Access-Control-Allow-Origin 관련 헤더 추가
- [CORS(Cross-Origin Resource Sharing)](https://developer.mozilla.org/en-US/docs/Glossary/CORS) 에러를 해결하기 위한 것
- 이러한 헤더는 HTTP 프로토콜 규약에 정의된 옵션 (nginx라서 존재하는 것이 아님)
- 브라우저와 백엔드 서버 사이에서 nginx가 HTTP 요청 및 응답을 전달하는 과정에서 발생
>  [이 블로그](https://imprint.tistory.com/m/287)에서 설명하는 상황1과 유사함
- always 옵션: 모든 HTTP 응답 코드에 대해 이 헤더를 포함시키라는 지시
```
add_header 'Access-Control-Allow-Origin' 'http://localhost:8080' always;
add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;
add_header …
```

[Setting] nginx.conf 파일에 CORS 에러 해결을 위한 헤더 추가

---

BE/users/urls.py
BE/users/views.py

회원가입에 필요한 필드 중복 검사 API 구현
- 이메일, 아이디, 닉네임을 쿼리 파라미터(`?`)로 받을 수 있음
- 예시: `http://localhost:8000/users/check/?username=jeongmin&email=yesuel1111@naver.com`
- 특정 필드 중 최소 1개 이상 존재해야 함
- 응답 결과
- 모두 중복되지 않을 시 200
- 중복된 값이 존재할 경우 409
- 쿼리 파라미터가 존재하지 않을 포함 시 400
- 허용되지 않은 쿼리 파라미터 포함 시 400
- `request.query_params`의 형태가 딕셔너리이지만 `value` 값이 배열 형태로 들어와서 `check_duplicate` 함수에서 `filter` 함수 사용 시 배열의 첫번째 값을 참조하도록 작성됨
- `filter`는 이전에 사용한 get과 달리 매칭되는 모든 값을 반환
- close #138

[Feat] 회원가입에 필요한 필드 중복 검사 API 구현

---

FE/public/css/styles.css
FE/src/components/DuelGraphStats.js
FE/src/components/DuelReport.js
FE/src/constants/apiConfig.js
FE/src/pages/DuelStatsPage.js
FE/src/pages/TournamentResultPage.js

- 모달-경기기록 그래프 canvas와 토너먼트 or 1vs1 결과 페이지 그래프 canvas 중복현상 해결
1. 모달의 경기 기록을 누르고 난 뒤, 토너먼트나 1vs1 대결을 진행
2. 게임이 끝난 후, 토너먼트-전체경기결과페이지 / 1vs1-경기결과 페이지에서 그래프 UI 를 그릴 때 오류 발생
- 모달을 생성하면서 기존에 있었던 코드들과 충돌이 나는 현상입니다.
- 모달에서 활용했던 똑같은 그래프 코드를 사용하기에 querySelector(), querySelectorAll() 함수에서 모달의 그래프 코드를 참조하는 오류가 발생합니다.
- 토너먼트-경기결과페이지 or 1vs1 경기결과 페이지에서의 클래스 이름을 변경하여 모달에서 사용한 그래프 코드의 클래스이름과 겹치지 않도록 합니다.
생략
#154

[Bug] canvas 중복 문제 해결

---

BE/rooms/room_manager.py
BE/users/serializers.py
BE/users/urls.py
BE/users/views.py

- 특정 접두사로 시작하는 닉네임을 가진 유저 검색 API 구현
- 특정 pk를 가진 유저 프로필 조회 API 구현
- `GET` `/users/search/?prefix=abc`
- 로그인시에만 동작
- DB에서 접두사로 시작하는 닉네임을 가진 매칭되는 모든 유저 리스트를 반환
`user_profile_list = User.objects.filter(nickname__startswith=prefix)`
- 200 OK (성공)
- - 400 Bad Request (잘못된 요청)
- 쿼리 파라미터에 `prefix`가 포함되지 않은 경우
- 403 Forbidden (로그인 하지 않고 요청 시)
- `GET` `/users/detail/<user_pk>`
- 로그인시에만 동작
- DB에서 pk에 해당하는 유저 프로필 반환
`user_profile = User.objects.get(pk=user_pk)`
- 프로필은 해당 유저의 pk, profile_url, nickname을 포함
- 추후 경기 요약 정보는 따로 API 구현 예정
- pk는 DB에서 자동으로 늘어나는 인덱스값(username(id)가 아님)
- 200 OK (성공)
- 404 Bad Request (잘못된 요청)
- 해당하는 pk를 가진 유저가 존재하지 않는 경우
- pk가 숫자가 아니라면 url이 매칭되지 않음
- 403 Forbidden (로그인 하지 않고 요청 시)
- #146

[Feat] 유저 검색 및 특정 유저 프로필 조회 API 구현

---

BE/rooms/services/room.py
BE/rooms/services/room_manager.py
BE/rooms/services/room_user.py
BE/websocket/room_consumer.py

방에 다양한 기능 추가
- 방장이 방을 나가면 해당 방을 삭제
- 방 내부에 있던 참가자들에게는 `type: room.end` 메시지를 보내고 웹소켓 연결을 끊음
- 해당 메시지를 받으면 '방이 종료되었습니다 ' 등의 메시지를 띄우고 홈으로 가게 하면 될 듯
- 유저가 `type: room.change.state` 메시지를 보내면 해당 유저의 상태를 변경
- 유저가 상태를 변경하면 방에 접속 중인 모두에게 갱신된 방 정보를 다시 보냄
- 유저가 `type: room.change.info` 메시지를 보내면 방 정보를 수정
- 난이도, 총점, 공 색깔, 패들 색깔만 수정 가능
- 메시지 형식
```json
{
"type": "room.change.info",
"data": {
"level":2,
"total_score":10,
"color":{
"paddle":"#5AD7FF",
"ball":"#FFD164"
},
}
}
```
- 현재는 방장이 아니더라도 해당 메시지를 전송하면 방의 상태를 바꿀 수 있는 취약점이 존재
- 이후에 해당 메시지를 보낸 유저가 방장인지 검사하여 방 수정 여부 결정하는 로직 추가 예정
- 같은 유저인지 판단하는 코드 리팩토링
- 기존에는 `room_user._nickname == user.nickname`으로 요청을 보낸 유저와 방 안에 있는 유저를 구분하고 있었음 -> protect 변수를 외부에서 참조하는 문제
- RoomUser가 같은 유저인지 판단하도록 `is_same()` 메서드 추가
- ex) `room_user.is_same(user)`
- 유저가 방을 나갈 경우 예외가 …

[Feat] 방 기능 추가(상태 변경, 방 정보 수정, 방 자동 삭제)

---

BE/users/views.py

- 친구 요청 전송 시 friend_pk를 int로 보냈을 경우 예외 처리
- 이미 친구일 때 요청 전송 시 예외 처리
- body에 포함된 friend_pk가 str이라고 가정하고 코드를 작성했더니 int의 경우 isdigit 함수가 존재하지 않아 500 예외 발생
- 받아온 데이터가 int 형이라면 그대로 사용하도록 코드 수정
400 Bad Request 발생 시 구분을 위해 에러 응답 전송 시 `code` 값 지정
**이는 친구 요청 전송 시 400 예외에서만 구분하기 위해 추가해두어 다른 예외 상태코드에는 없음**
- 본인에게 친구 요청 전송 → `FRIEND_ERROR_0`
- 이미 친구일 때 친구 요청 전송 → `FRIEND_ERROR_1`
- 친구 요청을 보낸 상태에서 친구 요청 전송 → `FRIEND_ERROR_2`
- 파싱 예외 발생 → `PARSE_ERROR`
- #179

[Hotfix] 친구 요청 전송 시 friend_pk를 int로 보냈을 경우, 중복 요청 예외 처리

---

FE/src/components/MyFriendRequestNode.js
FE/src/components/modal/profile_modal/FriendInfoContent.js
FE/src/components/modal/profile_modal/GetContent.js
FE/src/components/modal/profile_modal/MyFriendContent.js
FE/src/constants/apiConfig.js

친구 목록, 보낸 요청, 받은 요청 API 연결
- 친구 목록, 보낸 요청, 받은 요청 API 연결
- 친구 목록에서 친구 클릭 시 해당 정보 받아와서 모달로 연결
- 보낸 요청 삭제 시 삭제 반영
- 받은 요청 수락 시 친구 목록에 바로 업데이트
- 받은 요청 거절 시 삭제
- 처리된 건에 대한 비정상적 요청에 대해 "~에 실패했습니다."와 같은 문구로 실패 알림.
- 204의 경우 no content이고, 400의 경우 데이터가 전달되는 형태라 따로 처리하는 것은 시간을 잡아먹는 행위라고 판단
1. 친구 요청
2. 친구 수락
4. 친구 거절
5. 친구 요청 삭제
#178

[Feat] 친구 목록, 보낸 요청, 받은 요청 API 연결

---

FE/src/constants/constants.js
FE/src/game/MessageManager.js
FE/src/pages/online/rooms/waitingRoom/WaitingRoomPage.js

게임 중 score 관련 정보 서버에서 받아오도록 변경
1. 온라인 게임 종료 후 winner 애니메이션 추가되지 않는 오류 발생
2. 로컬 게임 진행 시 서버에서 받아온 정보가 아닌 기존 로컬이 가지고 있던 score 정보를 사용하고 있던 문제
3. 서버에서 보낸 메시지의 message를 판단하여 애니메이션 함수 실행
- ready animation
```
{
"type": "game",
"subtype": "match_run",
"message": "ready animation",
"data": {
...
}
}
```
- winner animation
- 서버에서 보낸 score을 비교하여 winner 결정 
```
{
"type": "game",
"subtype": "match_run",
"message": "winner animation",
"data": {
...
"score": {
"player1": 2,
"player2": 5
}
}
}
```
- close #197

[Fix] 게임 중 score 관련 정보 서버에서 받아오도록 변경

---

BE/stats/serializers.py
BE/stats/urls.py
BE/stats/views.py
BE/users/views.py
BE/websocket/game_server.py

유저 게임 통계 모달 데이터 조회 API 구현
> 자세한 형식은 [API 문서](https://www.notion.so/a791451934ed4a2cb290c7cac497af76?pvs=4)를 확인해주세요
`GET /stats/`
- serializer에 사용할 PlayTimeField 구현
- h, m, s 단위로 만들기 위해 새로 작성
- days는 모두 hours 단위로 합쳐서 처리
- UserStatSerializer는 UserStatSummarySerializer를 상속받아 구현
- 겹치는 데이터를 사용하기 위해 상속
- 추가로 필요한 필드 선언
- graph 데이터 생성
- 최근 진행한 12 경기 기준 (12경기보다 작게 진행했다면 그만큼만 반환)
- `match_cnt`: 경기 횟수(12경기보다 작은지 확인 필요)
- `rating_change`: 오른쪽으로 갈 수록 최근 매치 데이터(빈 배열일 수도 있음)
- `attack_type`: 공격 성향 카운트 (`TYPE0`: 공격형 / `TYPE1`: 방어형 / `TYPE2`: 혼합형)
- UserStat 정보가 없는 경우 생성하도록 코드 수정
- request_game_session post 요청 timeout 10초로 적용 (pylint 경고 제거)
- #122

[Feat] 유저 게임 통계 모달 데이터 조회 API 구현

---

BE/stats/models.py
BE/stats/serializers.py
BE/stats/tests.py
BE/stats/time_utils.py
BE/stats/urls.py
BE/stats/views.py
BE/users/views.py
GAME/websocket/backend_api.py
GAME/websocket/consumers.py

- 로컬 매치 기록 전송 API 구현 및 게임서버 반영
- 승률 퍼센트에 맞춰서 반환 값 수정
`POST /stats/match/local/`
- pk와 play_time을 받아 해당 유저에 로컬 플레이 타임 반영
- 204 No Content(반영), 400 Bad Reqeust (형식 오류), 404 Not Found (유저 정보를 찾을 수 없음)
- `time_utils.py`로 파일 분리
- 온라인과 마찬가지로 Consumer 내부 pk 저장
- 세션키가 있는지 확인하고 없으면 하지 않음
- `send_match_result` 함수에 인자로 mode 추가
- 이에 해당하는 처리도 함께 추가
- close #122

[Feat] 로컬 매치 기록 전송 API 구현 및 게임서버 반영

---

GAME/session/session_manager.py

토너먼트와 완라인 1대1에 랜덤 매치메이킹 추가
- 기존에는 따로 매치메이킹이 없었음
- random.shuffle 함수를 사용하여 닉네임 순서를 섞음
https://github.com/authenticity-house/ft_transcendence/assets/43935708/722be0c5-a2fa-4e44-934a-783eca989ad9
- close: #222

[Feat] 랜덤 매치메이킹 추가

---

FE/public/css/styles.css
FE/src/components/ModalGraphStats.js
FE/src/components/modal/profile_modal/StatsContent.js

- 모달 - 통계 공격성향 UI 수정
현재 파이 차트로 되어 있는 공격성향 UI의 부족한 점
- 파이 차트 안의 폰트 사이즈 16px 고정 되어 있어서, 특정 성향의 파이 차트가 작을 시 폰트가 오버플로우 되는 현상
- 파이 차트의 각 비율 %의 따른 폰트 사이즈 px 동적으로 변환
- 몇 경기를 해서 파이 차트가 만들어졌는지 모르는 상황
- 공격형, 혼합형, 방어형 횟수 텍스트 UI 추가
<hr>
#238

[Feat] 모달 - 통계 공격성향 UI 개선

---

FE/src/components/ModalGraphStats.js

레이팅 변화율 그래프 겹치는 현상 해결
- 게임 종료 후 모달 - 통계로 가면, 기존에 그렸던 레이팅 변화율 그래프 + 게임 종료 후 갱신된 레이팅 변화율의 그래프 둘 다 있는 현상이 발생하는 것을 확인했습니다.
- canvas를 그리기 전에 canvas 안의 모든 것들을 clear해주는 함수를 추가하여 문제를 해결했습니다.
- (+) 추가로 공격 성향 그래프에서 특정 값이 1이면, fontSize를 4로 설정했더니 너무 작아보여서 7로 재설정했습니다.
#242

[Hotfix] 레이팅 변화율 그래프 겹치는 현상 해결
